world:
  name: "farms"

messages:
  prefix: "<b><yellow>Farms</yellow><dark_gray>ã€‹<dark_gray></b> "

  admin:
    reload:
      success: "<green>Configuration reloaded.</green>"

    setup:
      creating-world: "<gray>Creating '<white>%world%</white>' void world...</gray>"
      already-exists: "<gray>World '<white>%world%</white>' already exists.</gray>"
      failed-create: "<red>Failed to create '<white>%world%</white>' world.</red>"
      created: "<green>'<white>%world%</white>' void world created.</green>"
      teleporting: "<gray>Teleporting you to the '<white>%world%</white>' spawn...</gray>"