world:
  name: "farms"

  spawn:
    x: 0
    y: 61
    z: 0

    platform:
      y: 60
      radius: 3
      material: "LIGHT_GRAY_STAINED_GLASS"

  keep_spawn_in_memory: false

  gamerules:
    do_mob_spawning: false
    do_daylight_cycle: false
    do_weather_cycle: false

placement:
  spacing: 3000
  spawn_buffer: 12000

schematics:
  paste_y: 60
  ignore_air: true

teleport:
  fallback_y: 61
